package com.github.coolcool.sloth.lianjiadb.service;

import com.github.coolcool.sloth.lianjiadb.common.Page;
import com.github.coolcool.sloth.lianjiadb.model.Area;

import javax.annotation.Generated;
import java.util.List;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public interface AreaService {

	Integer save(Area area);

	Integer count();

	Area getById(Object id);

	void deleteById(Object id);

	void update(Area area);

	List<Area> listAll();

	List<Area> listOneLevelChilden(int id);

	List<Area> listTwoLevelChilden(int id);

	Page<Area> page(int pageNo, int pageSize);

	Integer increment();
}