package com.github.coolcool.sloth.lianjiadb.service;
import java.util.*;
import com.github.coolcool.sloth.lianjiadb.model.House;
import com.github.coolcool.sloth.lianjiadb.common.Page;
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public interface HouseService{

	Integer save(House house);

	Integer count();

	House getById(Object id);

	House getByCode(String code);

	Boolean isExist(String code);

	void deleteById(Object id);

	void update(House house);

	void updateChengjiaoPriceByCode(String code, Double chengjiaoPrice);

	List<House> list();

	Page<House> page(int pageNo, int pageSize);

	Page<House> pageToday(int pageNo, int pageSize);

	Integer increment();
}