package com.github.coolcool.sloth.lianjiadb.service;
import java.util.*;
import com.github.coolcool.sloth.lianjiadb.model.Houseprice;
import com.github.coolcool.sloth.lianjiadb.common.Page;
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public interface HousepriceService{

	Integer save(Houseprice houseprice);

	Integer count();

	Houseprice getById(Object id);

	void deleteById(Object id);

	void update(Houseprice houseprice);

	List<Houseprice> list();

	Page<Houseprice> page(int pageNo, int pageSize);

	Integer increment();

	Houseprice getPrevious(String code);

	/**
	 * 精确到小数点后两位
	 * @param price
	 * @return
     */
	String format(Double price);


}