package com.github.coolcool.sloth.lianjiadb.service;

import com.github.coolcool.sloth.lianjiadb.common.Page;
import com.github.coolcool.sloth.lianjiadb.model.Httpproxy;

import javax.annotation.Generated;
import java.util.List;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public interface HttpproxyService{

	Integer save(Httpproxy httpproxy);

	Integer count();

	Httpproxy getById(Integer id);

	void deleteById(Integer id);

	void update(Httpproxy httpproxy);

	List<Httpproxy> list();

	Page<Httpproxy> page(int pageNo, int pageSize);

}