package com.github.coolcool.sloth.lianjiadb.mapper;
import java.util.*;
import com.github.coolcool.sloth.lianjiadb.model.Area;
import javax.annotation.Generated;
import org.apache.ibatis.annotations.*;

@Generated(
		value = {
				"https://github.com/coolcooldee/sloth",
				"Sloth version:1.0"
		},
		comments = "This class is generated by Sloth"
)
public interface AreaMapper{

	@Select("SELECT COUNT(*) FROM area ")
	Integer count();


	@Select("SELECT * FROM area WHERE id = #{primaryKey} LIMIT 1 ")
	Area getByPrimaryKey(@Param("primaryKey") Object primaryKey);


	@Delete("DELETE FROM area WHERE id = #{primaryKey} ")
	Integer deleteByPrimaryKey(@Param("primaryKey") Object primaryKey);

	@Update({
			"UPDATE area SET id=#{id}, name=#{name}, code=#{code}, link=#{link}, parentsId=#{parentsId}, parentsName=#{parentsName}, parentsCode=#{parentsCode}, level=#{level} where id = #{id}"
	})
	Integer updateByPrimaryKey(Area area);

	@Insert({
			"INSERT INTO area (id, name, code, link, parentsId, parentsName, parentsCode, level)",
			"VALUE (#{id}, #{name}, #{code}, #{link}, #{parentsId}, #{parentsName}, #{parentsCode}, #{level}) ON DUPLICATE KEY UPDATE id=#{id}"
	})
	Integer insert(Area area);


	@Select("SELECT * FROM area LIMIT 10 ")
	List<Area> list();

	@Select("SELECT * FROM area ")
	List<Area> listAll();

	@Select("SELECT * FROM area where  parentsId=#{parentsId}")
	List<Area> listOneLevelChilden(@Param("parentsId") int parentsId);

	@Select("SELECT * FROM area where  parentsId in (select id from area where parentsId=#{parentsId})")
	List<Area> listTwoLevelChilden(@Param("parentsId") int parentsId);


	@Select("SELECT * FROM area LIMIT #{start}, #{step}")
	List<Area> page(@Param("start") int start, @Param("step") int step );


	@Select("SELECT `AUTO_INCREMENT` as number FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'area'")
	Integer increment();

}