package com.github.coolcool.sloth.lianjiadb.mapper;
import java.util.*;
import com.github.coolcool.sloth.lianjiadb.model.Houseprice;
import javax.annotation.Generated;
import org.apache.ibatis.annotations.*;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public interface HousepriceMapper{

	@Select("SELECT COUNT(*) FROM houseprice ")
	Integer count();


	@Select("SELECT * FROM houseprice WHERE id = #{primaryKey} LIMIT 1 ")
	Houseprice getByPrimaryKey(@Param("primaryKey") Object primaryKey);


	@Delete("DELETE FROM houseprice WHERE id = #{primaryKey} ")
	Integer deleteByPrimaryKey(@Param("primaryKey") Object primaryKey);

	@Update({
		"UPDATE houseprice SET id=#{id}, code=#{code}, price=#{price}, date=#{date} where id = #{id}"
	})
	Integer updateByPrimaryKey(Houseprice houseprice);

	@Insert({
		"INSERT INTO houseprice (code, price, date)",
		"VALUE (#{code}, #{price}, curdate()) ON DUPLICATE KEY UPDATE code=#{code}"
	})
	Integer insert(Houseprice houseprice);


	@Select("SELECT * FROM houseprice LIMIT 10 ")
	List<Houseprice> list();

	@Select("SELECT * FROM houseprice where code=#{code} order by date desc LIMIT 1 ")
	List<Houseprice> listNewest(@Param("code") String code);


	@Select("SELECT * FROM houseprice LIMIT #{start}, #{step}")
	List<Houseprice> page(@Param("start") int start, @Param("step") int step);


	@Select("SELECT `AUTO_INCREMENT` as number FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'houseprice'")
	Integer increment();
	
}