package com.github.coolcool.sloth.lianjiadb.mapper;
import java.util.*;
import com.github.coolcool.sloth.lianjiadb.model.Process;
import javax.annotation.Generated;
import org.apache.ibatis.annotations.*;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public interface ProcessMapper{

	@Select("SELECT COUNT(*) FROM process ")
	Integer count();


	@Select("SELECT * FROM process WHERE id = #{primaryKey} LIMIT 1 ")
	Process getByPrimaryKey(@Param("primaryKey") Object primaryKey);


	@Delete("DELETE FROM process WHERE id = #{primaryKey} ")
	Integer deleteByPrimaryKey(@Param("primaryKey") Object primaryKey);

	@Update({
		"UPDATE process SET id=#{id}, area=#{area}, pageNo=#{pageNo}, finished=#{finished}, createtime=#{createtime}, finishtime=#{finishtime} where id = #{id}"
	})
	Integer updateByPrimaryKey(Process process);

	@Insert({
		"INSERT INTO process (area, pageNo, finished, type, createtime)",
		"VALUE (#{area}, #{pageNo}, #{finished}, #{type},curdate()) ON DUPLICATE KEY UPDATE area=#{area}"
	})
	Integer insert(Process process);


	@Select("SELECT * FROM process LIMIT 50 ")
	List<Process> list();

	@Select("SELECT * FROM process where finished=0  ")
	List<Process> listUnFinished();


	@Select("SELECT * FROM process LIMIT #{start}, #{step}")
	List<Process> page(@Param("start") int start, @Param("step") int step );


	@Select("SELECT `AUTO_INCREMENT` as number FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 'process'")
	Integer increment();


	@Select("SELECT COUNT(*) FROM process where area=#{area} and createtime = curdate()")
	Integer countTodayProcessByAreaCode(@Param("area") String areaCode);

}