package com.github.coolcool.sloth.lianjiadb.model;

import com.alibaba.fastjson.annotation.JSONField;
import javax.annotation.Generated;
import java.math.BigDecimal;
import java.util.Date;

@Generated(
	value = {
	"https://github.com/coolcooldee/sloth",
	"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public class House {

	public House(String url) {
		this.url = url;
		String[] t = url.split("/");
		this.code = t[t.length-1].replace(".html","");
		//view-source:http://gz.lianjia.com/ershoufang/GZ0001384019.html
	}

	public House() {

	}

	private Long id;

	private String code;

	private String url;
	/**
	   
	 */
	private String title;
	/**
	   
	 */
	private String subtitle;
	/**
	   
	 */
	private Integer favcount = 0 ;
	/**
	   
	 */
	private Integer cartcount = 0;
	/**
	   
	 */
	private Double price;
	/**
	   
	 */
	private Double unitprice;
	/**
	   
	 */
	private Double firstPayPrice;
	/**
	   
	 */
	private Double taxPrice;
	/**
	   
	 */
	private String roomMainInfo;
	/**
	   
	 */
	private String roomSubInfo;
	/**
	   
	 */
	private String roomMainType;
	/**
	   
	 */
	private String roomSubType;
	/**
	   
	 */
	private String areaMainInfo;
	/**
	   
	 */
	private String areaSubInfo;
	/**
	   
	 */
	private String communityName;
	/**
	   
	 */
	private String areaName;
	/**
	   
	 */
	private String schoolName;
	/**
	   
	 */
	private String tags;
	/**

	 */
	private String decoratingDesc;
	/**
	   
	 */
	private String houseTypeDesc;
	/**
	   
	 */
	private String investmentDesc;
	/**
	   
	 */
	private String villageDesc;
	/**
	   
	 */
	private String schoolDesc;
	/**
	   
	 */
	private String sellingPointDesc;
	/**
	   
	 */
	private String reason4saleDesc;
	/**
	   
	 */
	private String supportingDesc;
	/**
	   
	 */
	private String trafficDesc;
	/**
	   
	 */
	private java.util.Date createtime;
	/**
	   
	 */
	private String baseContent1;
	/**
	   
	 */
	private String baseContent2;
	/**
	   
	 */
	private String baseContent3;
	/**
	   
	 */
	private String baseContent4;
	/**
	   
	 */
	private String baseContent5;
	/**
	   
	 */
	private String baseContent6;
	/**
	   
	 */
	private String baseContent7;
	/**
	   
	 */
	private String baseContent8;
	/**
	   
	 */
	private String baseContent9;
	/**
	   
	 */
	private String baseContent10;
	/**
	   
	 */
	private String baseContent11;
	/**
	   
	 */
	private String baseContent12;
	/**
	   
	 */
	private String transactionContent1;
	/**
	   
	 */
	private String transactionContent2;
	/**
	   
	 */
	private String transactionContent3;
	/**
	   
	 */
	private String transactionContent4;
	/**
	   
	 */
	private String transactionContent5;
	/**
	   
	 */
	private String transactionContent6;
	/**
	   
	 */
	private String transactionContent7;
	/**
	   
	 */
	private String transactionContent8;
	/**
	   
	 */
	private String transactionContent9;
	/**
	   
	 */
	private String transactionContent10;

	@JSONField(serialize=false)
	private  String html;

	private  double roomSize;
	/**
	 * 0:未处理；1:在售；2:已成交；-1:已经下架；-2：信息异常；-301：找不到
	 */
	private Integer status;

	private Double chengjiaoPrice;

	private Date chengjiaoDate;


	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	} 
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	} 
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	} 
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	} 
	public String getSubtitle() {
		return subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	} 
	public Integer getFavcount() {
		return favcount;
	}

	public void setFavcount(Integer favcount) {
		this.favcount = favcount;
	} 
	public Integer getCartcount() {
		return cartcount;
	}

	public void setCartcount(Integer cartcount) {
		this.cartcount = cartcount;
	} 
	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getUnitprice() {
		return unitprice;
	}

	public void setUnitprice(Double unitprice) {
		this.unitprice = unitprice;
	}

	public Double getFirstPayPrice() {
		return firstPayPrice;
	}

	public void setFirstPayPrice(Double firstPayPrice) {
		this.firstPayPrice = firstPayPrice;
	}

	public Double getTaxPrice() {
		return taxPrice;
	}

	public void setTaxPrice(Double taxPrice) {
		this.taxPrice = taxPrice;
	}

	public String getRoomMainInfo() {
		return roomMainInfo;
	}

	public void setRoomMainInfo(String roomMainInfo) {
		this.roomMainInfo = roomMainInfo;
	} 
	public String getRoomSubInfo() {
		return roomSubInfo;
	}

	public void setRoomSubInfo(String roomSubInfo) {
		this.roomSubInfo = roomSubInfo;
	} 
	public String getRoomMainType() {
		return roomMainType;
	}

	public void setRoomMainType(String roomMainType) {
		this.roomMainType = roomMainType;
	} 
	public String getRoomSubType() {
		return roomSubType;
	}

	public void setRoomSubType(String roomSubType) {
		this.roomSubType = roomSubType;
	} 
	public String getAreaMainInfo() {
		return areaMainInfo;
	}

	public void setAreaMainInfo(String areaMainInfo) {
		this.areaMainInfo = areaMainInfo;
	} 
	public String getAreaSubInfo() {
		return areaSubInfo;
	}

	public void setAreaSubInfo(String areaSubInfo) {
		this.areaSubInfo = areaSubInfo;
	} 
	public String getCommunityName() {
		return communityName;
	}

	public void setCommunityName(String communityName) {
		this.communityName = communityName;
	} 
	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	} 
	public String getSchoolName() {
		return schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	} 
	public String getTags() {
		return tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	} 
	public String getDecoratingDesc() {
		return decoratingDesc;
	}

	public void setDecoratingDesc(String decoratingDesc) {
		this.decoratingDesc = decoratingDesc;
	} 
	public String getHouseTypeDesc() {
		return houseTypeDesc;
	}

	public void setHouseTypeDesc(String houseTypeDesc) {
		this.houseTypeDesc = houseTypeDesc;
	} 
	public String getInvestmentDesc() {
		return investmentDesc;
	}

	public void setInvestmentDesc(String investmentDesc) {
		this.investmentDesc = investmentDesc;
	} 
	public String getVillageDesc() {
		return villageDesc;
	}

	public void setVillageDesc(String villageDesc) {
		this.villageDesc = villageDesc;
	} 
	public String getSchoolDesc() {
		return schoolDesc;
	}

	public void setSchoolDesc(String schoolDesc) {
		this.schoolDesc = schoolDesc;
	} 
	public String getSellingPointDesc() {
		return sellingPointDesc;
	}

	public void setSellingPointDesc(String sellingPointDesc) {
		this.sellingPointDesc = sellingPointDesc;
	} 
	public String getReason4saleDesc() {
		return reason4saleDesc;
	}

	public void setReason4saleDesc(String reason4saleDesc) {
		this.reason4saleDesc = reason4saleDesc;
	} 
	public String getSupportingDesc() {
		return supportingDesc;
	}

	public void setSupportingDesc(String supportingDesc) {
		this.supportingDesc = supportingDesc;
	} 
	public String getTrafficDesc() {
		return trafficDesc;
	}

	public void setTrafficDesc(String trafficDesc) {
		this.trafficDesc = trafficDesc;
	} 
	public java.util.Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(java.util.Date createtime) {
		this.createtime = createtime;
	} 
	public String getBaseContent1() {
		return baseContent1;
	}

	public void setBaseContent1(String baseContent1) {
		this.baseContent1 = baseContent1;
	} 
	public String getBaseContent2() {
		return baseContent2;
	}

	public void setBaseContent2(String baseContent2) {
		this.baseContent2 = baseContent2;
	} 
	public String getBaseContent3() {
		return baseContent3;
	}

	public void setBaseContent3(String baseContent3) {
		this.baseContent3 = baseContent3;
	} 
	public String getBaseContent4() {
		return baseContent4;
	}

	public void setBaseContent4(String baseContent4) {
		this.baseContent4 = baseContent4;
	} 
	public String getBaseContent5() {
		return baseContent5;
	}

	public void setBaseContent5(String baseContent5) {
		this.baseContent5 = baseContent5;
	} 
	public String getBaseContent6() {
		return baseContent6;
	}

	public void setBaseContent6(String baseContent6) {
		this.baseContent6 = baseContent6;
	} 
	public String getBaseContent7() {
		return baseContent7;
	}

	public void setBaseContent7(String baseContent7) {
		this.baseContent7 = baseContent7;
	} 
	public String getBaseContent8() {
		return baseContent8;
	}

	public void setBaseContent8(String baseContent8) {
		this.baseContent8 = baseContent8;
	} 
	public String getBaseContent9() {
		return baseContent9;
	}

	public void setBaseContent9(String baseContent9) {
		this.baseContent9 = baseContent9;
	} 
	public String getBaseContent10() {
		return baseContent10;
	}

	public void setBaseContent10(String baseContent10) {
		this.baseContent10 = baseContent10;
	} 
	public String getBaseContent11() {
		return baseContent11;
	}

	public void setBaseContent11(String baseContent11) {
		this.baseContent11 = baseContent11;
	} 
	public String getBaseContent12() {
		return baseContent12;
	}

	public void setBaseContent12(String baseContent12) {
		this.baseContent12 = baseContent12;
	} 
	public String getTransactionContent1() {
		return transactionContent1;
	}

	public void setTransactionContent1(String transactionContent1) {
		this.transactionContent1 = transactionContent1;
	} 
	public String getTransactionContent2() {
		return transactionContent2;
	}

	public void setTransactionContent2(String transactionContent2) {
		this.transactionContent2 = transactionContent2;
	} 
	public String getTransactionContent3() {
		return transactionContent3;
	}

	public void setTransactionContent3(String transactionContent3) {
		this.transactionContent3 = transactionContent3;
	} 
	public String getTransactionContent4() {
		return transactionContent4;
	}

	public void setTransactionContent4(String transactionContent4) {
		this.transactionContent4 = transactionContent4;
	} 
	public String getTransactionContent5() {
		return transactionContent5;
	}

	public void setTransactionContent5(String transactionContent5) {
		this.transactionContent5 = transactionContent5;
	} 
	public String getTransactionContent6() {
		return transactionContent6;
	}

	public void setTransactionContent6(String transactionContent6) {
		this.transactionContent6 = transactionContent6;
	} 
	public String getTransactionContent7() {
		return transactionContent7;
	}

	public void setTransactionContent7(String transactionContent7) {
		this.transactionContent7 = transactionContent7;
	} 
	public String getTransactionContent8() {
		return transactionContent8;
	}

	public void setTransactionContent8(String transactionContent8) {
		this.transactionContent8 = transactionContent8;
	} 
	public String getTransactionContent9() {
		return transactionContent9;
	}

	public void setTransactionContent9(String transactionContent9) {
		this.transactionContent9 = transactionContent9;
	} 
	public String getTransactionContent10() {
		return transactionContent10;
	}

	public void setTransactionContent10(String transactionContent10) {
		this.transactionContent10 = transactionContent10;
	}

	public String getHtml() {
		return html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

	public double getRoomSize() {
		return roomSize;
	}

	public void setRoomSize(double roomSize) {
		this.roomSize = roomSize;
	}

	public Double getChengjiaoPrice() {
		return chengjiaoPrice;
	}

	public void setChengjiaoPrice(Double chengjiaoPrice) {
		this.chengjiaoPrice = chengjiaoPrice;
	}

	public Date getChengjiaoDate() {
		return chengjiaoDate;
	}

	public void setChengjiaoDate(Date chengjiaoDate) {
		this.chengjiaoDate = chengjiaoDate;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
}
