package com.github.coolcool.sloth.lianjiadb.model;

import javax.annotation.Generated;

@Generated(
	value = {
	"https://github.com/coolcooldee/sloth",
	"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public class Httpproxy {

	private Integer id;
	private String host;
	private Integer port;
	private String username;
	private String password;
	private java.util.Date createtime;
	private java.util.Date updatetime;
	private Integer status;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	} 
	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	} 
	public Integer getPort() {
		return port;
	}

	public void setPort(Integer port) {
		this.port = port;
	} 
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	} 
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	} 
	public java.util.Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(java.util.Date createtime) {
		this.createtime = createtime;
	} 
	public java.util.Date getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(java.util.Date updatetime) {
		this.updatetime = updatetime;
	} 
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	} 
}
